### ISSUE TITLE
很强！请教下多条线1个calldraw的原理是什么？

### ISSUE THREAD

**Issue by GITHUB243884919** [871041532/SLGDrawLine#2]
很强！请教下多条线1个calldraw的原理是什么？谢谢

**Comment by 871041532** [comment]
所有的线都使用了相同材质，Unity自动进行了动态合批

**Comment by GITHUB243884919** [comment]
> 所有的线都使用了相同材质，Unity自动进行了动态合批

哦，那如果是这样，用linerender也能在一个calldraw
